/**
 * generate-knowledge-base.ts — YAML → TypeScript constant generation
 *
 * Reads data/structured/parentos/*.yaml and produces typed TS constants
 * in src/shell/renderer/knowledge-base/gen/.
 *
 * @generated — run via `pnpm generate:knowledge-base`
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';
import { readKnowledgeAssetData } from './knowledge-json-asset.js';
import { loadKnowledgeAsset } from './knowledge-asset-kernel.js';
import {
  ACTION_TYPE_TO_KIND,
  liftOrthodonticRules,
  type BaseReminderRule,
} from './generate-knowledge-base-reminders.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TABLES = resolve(ROOT, 'data/structured/parentos');
const DATA_KNOWLEDGE = resolve(ROOT, 'data/knowledge');
const OUT = resolve(ROOT, 'src/shell/renderer/knowledge-base/gen');
const RUST_OUT = resolve(ROOT, 'src-tauri/src/sqlite/queries');

mkdirSync(OUT, { recursive: true });
mkdirSync(RUST_OUT, { recursive: true });

const HEADER = `// @generated — do not edit manually\n// Generated by scripts/generate-knowledge-base.ts\n\n`;

function readYaml(filename: string): unknown {
  const raw = readFileSync(resolve(TABLES, filename), 'utf-8');
  return parseYaml(raw);
}

function readKnowledgeAsset(assetId: string): unknown {
  return readKnowledgeAssetData(DATA_KNOWLEDGE, assetId);
}

const KNOWLEDGE_ASSET_IDS = [
  'growth-standards',
  'milestone-catalog',
  'sensitive-periods',
  'observation-framework',
  'ability-model',
  'ai-boundary-rules',
  'advisor-classifier',
  'pediatric-drug-catalog',
  'journal-guidance-catalog',
  'smart-alert-rules',
] as const;

function loadKnowledgeAssetForProjection(assetId: string) {
  return loadKnowledgeAsset({
    dataKnowledgeRoot: DATA_KNOWLEDGE,
    assetId,
    manifestPath: resolve(DATA_KNOWLEDGE, 'assets', assetId, 'asset.json'),
  });
}

function writeGen(filename: string, content: string) {
  writeFileSync(resolve(OUT, filename), HEADER + content, 'utf-8');
  console.log(`  wrote ${filename}`);
}

function rustString(value: string) {
  return JSON.stringify(value);
}

function writeRustGen(filename: string, content: string) {
  writeFileSync(resolve(RUST_OUT, filename), `// @generated - do not edit manually\n// Generated by scripts/generate-knowledge-base.ts\n\n${content}`, 'utf-8');
  console.log(`  wrote ${filename}`);
}

// ── reminder-rules ──────────────────────────────────────────

function generateReminderRules() {
  const data = readYaml('reminder-rules.yaml') as { rules: BaseReminderRule[] };
  const extendedData = readYaml('reminder-rules-extended.yaml') as { rules: BaseReminderRule[] };
  const orthoRules = liftOrthodonticRules(readYaml);
  const merged: BaseReminderRule[] = [...data.rules, ...extendedData.rules, ...orthoRules];

  // Enforce unique ruleIds across the union.
  const seen = new Set<string>();
  for (const rule of merged) {
    if (seen.has(rule.ruleId)) {
      throw new Error(
        `generate-knowledge-base: duplicate ruleId "${rule.ruleId}" detected while unioning data/structured/parentos/reminder-rules.yaml with data/structured/parentos/orthodontic-protocols.yaml`,
      );
    }
    seen.add(rule.ruleId);
  }

  // Enforce PO-TIME-009: orthodontic protocol rules must be push in all modes.
  for (const rule of orthoRules) {
    if (rule.ruleId.startsWith('PO-ORTHO-')) {
      for (const mode of ['relaxed', 'balanced', 'advanced'] as const) {
        if (rule.nurtureMode[mode] !== 'push') {
          throw new Error(
            `generate-knowledge-base: orthodontic rule "${rule.ruleId}" must be push in all nurture modes (PO-TIME-009); got ${mode}=${rule.nurtureMode[mode]}`,
          );
        }
      }
    }
  }

  // PO-REMI-002: enforce actionType ↔ kind mapping for every merged rule.
  for (const rule of merged) {
    const expected = ACTION_TYPE_TO_KIND[rule.actionType];
    if (!expected) {
      throw new Error(
        `generate-knowledge-base: rule "${rule.ruleId}" has unknown actionType '${rule.actionType}'`,
      );
    }
    if (rule.kind !== expected) {
      throw new Error(
        `generate-knowledge-base: rule "${rule.ruleId}" kind '${rule.kind}' does not match PO-REMI-002 mapping for actionType '${rule.actionType}' (expected '${expected}')`,
      );
    }
  }

  const domains = [...new Set(merged.map((r) => r.domain))].sort();
  const categories = [...new Set(merged.map((r) => r.category))].sort();
  const priorities = [...new Set(merged.map((r) => r.priority))].sort();
  const actionTypes = [...new Set(merged.map((r) => r.actionType))].sort();
  const kinds = [...new Set(merged.map((r) => r.kind))].sort();

  const ts = `
export type ReminderDomain = ${domains.map((d) => `'${d}'`).join(' | ')};
export type ReminderCategory = ${categories.map((c) => `'${c}'`).join(' | ')};
export type ReminderPriority = ${priorities.map((p) => `'${p}'`).join(' | ')};
export type ReminderVisibility = 'push' | 'silent' | 'hidden';
export type ActionType = ${actionTypes.map((a) => `'${a}'`).join(' | ')};
export type ReminderKind = ${kinds.map((k) => `'${k}'`).join(' | ')};

export interface ReminderExplainSource {
  citation: string;
  url?: string;
}

export interface ReminderExplain {
  whyNow: string;
  howTo: readonly string[];
  doneWhen: string;
  ifNotNow?: string;
  pitfalls?: readonly string[];
  sources: readonly ReminderExplainSource[];
}

export type ReminderRepeatCadenceUnit = 'day' | 'week' | 'month';

export interface ReminderRepeatRule {
  cadenceUnit: ReminderRepeatCadenceUnit;
  interval: number;
  maxRepeats: number;
}

export interface ReminderRule {
  ruleId: string;
  domain: ReminderDomain;
  category: ReminderCategory;
  kind: ReminderKind;
  title: string;
  description: string;
  triggerAge: { startMonths: number; endMonths: number };
  triggerCondition?: { dataField: string; operator: string; value: unknown };
  priority: ReminderPriority;
  nurtureMode: { relaxed: ReminderVisibility; balanced: ReminderVisibility; advanced: ReminderVisibility };
  actionType: ActionType;
  repeatRule?: ReminderRepeatRule;
  explain?: ReminderExplain;
  expiryMonths?: number;
  tags?: readonly string[];
}

export const REMINDER_RULES: readonly ReminderRule[] = ${JSON.stringify(merged, null, 2)};

export const REMINDER_DOMAINS = ${JSON.stringify(domains)} ;
export const REMINDER_KINDS = ${JSON.stringify(kinds)} ;
`;

  writeGen('reminder-rules.gen.ts', ts);
  const vaccineRuleIds = merged
    .filter((rule) => rule.domain === 'vaccine')
    .map((rule) => rule.ruleId);
  const vaccineRustRows = vaccineRuleIds
    .map((ruleId) => `    ${rustString(ruleId)},`)
    .join('\n');
  writeRustGen(
    'vaccine-reminder-rules.gen.rs',
    `pub(crate) static VACCINE_REMINDER_RULE_IDS: &[&str] = &[\n${vaccineRustRows}\n];\n`,
  );
}

// ── milestone-catalog ──────────────────────────────────────

function generateMilestoneCatalog() {
  const data = readKnowledgeAsset('milestone-catalog') as {
    milestones: Array<{
      milestoneId: string;
      domain: string;
      title: string;
      description: string;
      typicalAge: { medianMonths: number; rangeStart: number; rangeEnd: number };
      alertIfNotBy?: number;
      source: string;
    }>;
  };

  const domains = [...new Set(data.milestones.map((m) => m.domain))].sort();

  const ts = `
export type MilestoneDomain = ${domains.map((d) => `'${d}'`).join(' | ')};

export interface Milestone {
  milestoneId: string;
  domain: MilestoneDomain;
  title: string;
  description: string;
  typicalAge: { medianMonths: number; rangeStart: number; rangeEnd: number };
  alertIfNotBy?: number;
  source: string;
}

export const MILESTONE_CATALOG: readonly Milestone[] = ${JSON.stringify(data.milestones, null, 2)} ;

export const MILESTONE_DOMAINS = ${JSON.stringify(domains)} ;
`;

  writeGen('milestone-catalog.gen.ts', ts);
}

// ── sensitive-periods ──────────────────────────────────────

function generateSensitivePeriods() {
  const data = readKnowledgeAsset('sensitive-periods') as {
    periods: Array<{
      periodId: string;
      title: string;
      description: string;
      ageRange: { startMonths: number; peakMonths: number; endMonths: number };
      observableSigns: string[];
      supportStrategies: string[];
      commonMistakes: string[];
      source: string;
    }>;
  };

  const ts = `
export interface SensitivePeriod {
  periodId: string;
  title: string;
  description: string;
  ageRange: { startMonths: number; peakMonths: number; endMonths: number };
  observableSigns: string[];
  supportStrategies: string[];
  commonMistakes: string[];
  source: string;
}

export const SENSITIVE_PERIODS: readonly SensitivePeriod[] = ${JSON.stringify(data.periods, null, 2)} ;
`;

  writeGen('sensitive-periods.gen.ts', ts);
}

// ── observation-framework ──────────────────────────────────

function generateObservationFramework() {
  const data = readKnowledgeAsset('observation-framework') as {
    observationModes: Array<{
      modeId: string;
      displayName: string;
      description: string;
      duration: string;
      format: string;
      frequency: string;
      guidancePrompt: string;
      tips?: string[];
    }>;
    frameworkMapping: {
      layers: Array<{
        ageRange: { startMonths: number; endMonths: number };
        primaryFramework: string;
        dimensions: string[];
      }>;
    };
    dimensions: Array<Record<string, unknown>>;
  };

  const modeIds = data.observationModes.map((m) => m.modeId);
  const rawDims = data.dimensions ?? [];
  const dimIds = rawDims.map((d) => d.dimensionId as string);
  // Project dimension data: YAML uses ageRelevance + indicators, interface normalizes to ageRange + observableSignals
  const cleanDims = rawDims.map((d) => ({
    dimensionId: d.dimensionId as string,
    displayName: d.displayName as string,
    description: (d.description as string) ?? '',
    ageRange: (d.ageRelevance as { startMonths: number; endMonths: number }) ?? { startMonths: 0, endMonths: -1 },
    parentQuestion: (d.parentQuestion as string) ?? '',
    observableSignals: Array.isArray(d.indicators) ? (d.indicators as Array<{ signal: string }>).map((i) => i.signal) : [],
    guidedQuestions: (d.guidedQuestions as string[]) ?? [],
    quickTags: (d.quickTags as string[]) ?? [],
    source: (d.source as string) ?? '',
  }));

  const ts = `
export type ObservationModeId = ${modeIds.map((m) => `'${m}'`).join(' | ')};

export interface ObservationMode {
  modeId: ObservationModeId;
  displayName: string;
  description: string;
  duration: string;
  format: string;
  frequency: string;
  guidancePrompt: string | null;
  tips?: string[];
  notes?: string[];
}

export interface ObservationDimension {
  dimensionId: string;
  displayName: string;
  description: string;
  ageRange: { startMonths: number; endMonths: number };
  parentQuestion: string;
  observableSignals: string[];
  guidedQuestions: string[];
  quickTags: string[];
  source: string;
}

export interface FrameworkLayer {
  ageRange: { startMonths: number; endMonths: number };
  primaryFramework: string;
  dimensions: string[];
}

export const OBSERVATION_MODES: readonly ObservationMode[] = ${JSON.stringify(data.observationModes, null, 2)} ;

export const OBSERVATION_DIMENSIONS: readonly ObservationDimension[] = ${JSON.stringify(cleanDims, null, 2)} ;

export const FRAMEWORK_LAYERS: readonly FrameworkLayer[] = ${JSON.stringify(data.frameworkMapping?.layers ?? [], null, 2)} ;

export const DIMENSION_IDS = ${JSON.stringify(dimIds)} ;
`;

  writeGen('observation-framework.gen.ts', ts);
  const rustRows = cleanDims
    .map((dimension) => {
      const tags = dimension.quickTags.map((tag) => rustString(tag)).join(', ');
      return `    (${rustString(dimension.dimensionId)}, &[${tags}]),`;
    })
    .join('\n');
  writeRustGen(
    'observation-vocabulary.gen.rs',
    `pub(crate) static OBSERVATION_VOCABULARY_ENTRIES: &[(&str, &[&str])] = &[\n${rustRows}\n];\n`,
  );
}

// ── growth-standards ───────────────────────────────────────

function generateGrowthStandards() {
  const data = readKnowledgeAsset('growth-standards') as {
    measurementTypes: Array<{
      typeId: string;
      displayName: string;
      unit: string;
      precision: number;
      ageRange: { startMonths: number; endMonths: number };
      referenceCoverage?: { startMonths: number; endMonths: number };
      frequency: string;
      standardSource: string;
      standardSourceIds?: string[];
      curveType: string;
    }>;
    referenceRanges?: Record<string, unknown>;
  };

  const typeIds = data.measurementTypes.map((t) => t.typeId);

  const ts = `
export type GrowthTypeId = ${typeIds.map((t) => `'${t}'`).join(' | ')};
export type CurveType = 'lms-percentile' | 'reference-range';

export interface GrowthStandard {
  typeId: GrowthTypeId;
  displayName: string;
  unit: string;
  precision: number;
  ageRange: { startMonths: number; endMonths: number };
  referenceCoverage?: { startMonths: number; endMonths: number };
  frequency: string;
  standardSource: string;
  standardSourceIds?: readonly string[];
  curveType: CurveType;
}

export const GROWTH_STANDARDS: readonly GrowthStandard[] = ${JSON.stringify(data.measurementTypes, null, 2)} ;

export const GROWTH_TYPE_IDS = ${JSON.stringify(typeIds)} ;

export const REFERENCE_RANGES = ${JSON.stringify(data.referenceRanges ?? {}, null, 2)} ;
`;

  writeGen('growth-standards.gen.ts', ts);
}

// ── nurture-modes ──────────────────────────────────────────

function generateNurtureModes() {
  const data = readYaml('nurture-modes.yaml') as {
    modes: Array<{
      modeId: string;
      displayName: string;
      subtitle: string;
      description: string;
      parameters: {
        reminderBehavior: { P0: string; P1: string; P2: string; P3: string };
        pushFrequency: { maxDailyPush: number; digestMode: string };
        contentDepth: string;
        aiAnalysisDetail: string;
        comparisonDisplay: string;
        milestoneTracking: string;
        interestGuidance: string;
        toneStyle: string;
      };
    }>;
  };

  const modeIds = data.modes.map((m) => m.modeId);

  const ts = `
export type NurtureModeId = ${modeIds.map((m) => `'${m}'`).join(' | ')};

export interface NurtureModeConfig {
  modeId: NurtureModeId;
  displayName: string;
  subtitle: string;
  description: string;
  parameters: {
    reminderBehavior: { P0: 'push'; P1: string; P2: string; P3: string };
    pushFrequency: { maxDailyPush: number; digestMode: string };
    contentDepth: string;
    aiAnalysisDetail: string;
    comparisonDisplay: string;
    milestoneTracking: string;
    interestGuidance: string;
    toneStyle: string;
  };
}

export const NURTURE_MODES: readonly NurtureModeConfig[] = ${JSON.stringify(data.modes, null, 2)} ;

export const NURTURE_MODE_IDS = ${JSON.stringify(modeIds)} ;
`;

  writeGen('nurture-modes.gen.ts', ts);
}

// ── knowledge-source-readiness ─────────────────────────────

function generateKnowledgeSourceReadiness() {
  const data = readYaml('knowledge-source-readiness.yaml') as {
    sources: Array<{
      domain: string;
      source: string;
      sourceLevel: string;
      status: string;
      owner: string;
      lastReviewedAt: string | null;
      notes: string;
    }>;
  };

  const reviewed = data.sources.filter((s) => s.status === 'reviewed').map((s) => s.domain);
  const needsReview = data.sources.filter((s) => s.status === 'needs-review').map((s) => s.domain);

  const ts = `
export type KnowledgeSourceStatus = 'reviewed' | 'needs-review';

export interface KnowledgeSource {
  domain: string;
  source: string;
  sourceLevel: string;
  status: KnowledgeSourceStatus;
  owner: string;
  lastReviewedAt: string | null;
  notes: string;
}

export const KNOWLEDGE_SOURCES: readonly KnowledgeSource[] = ${JSON.stringify(data.sources, null, 2)} ;

/** Domains that have been reviewed and can be used in AI prompts */
export const REVIEWED_DOMAINS: readonly string[] = ${JSON.stringify(reviewed)} ;

/** Domains that need review — rules engine and static display only, NO AI free generation */
export const NEEDS_REVIEW_DOMAINS: readonly string[] = ${JSON.stringify(needsReview)} ;
`;

  writeGen('knowledge-source-readiness.gen.ts', ts);
}

// ── dashboard-task-catalog ─────────────────────────────────

function generateDashboardTaskCatalog() {
  const data = readYaml('dashboard-task-catalog.yaml') as {
    rows: Array<Record<string, unknown>>;
  };

  const ts = `
export type DashboardTaskFamily = 'must-do' | 'maintain' | 'observe' | 'connect';
export type DashboardTaskCadencePolicy = 'anchor' | 'interval' | 'windowed';
export type DashboardTaskBiologicalAnchor = 'birthDayOfMonth' | 'none';
export type DashboardTaskSlotPreference = 'weekend-heavy' | 'weekday-evening-light' | 'hard-time';
export type DashboardTaskDispersionWindow = 'week-1' | 'week-2' | 'week-3' | 'week-4' | 'rolling';
export type DashboardTaskDecayStrategy = 'low-disturbance-downgrade' | 'resurface-next-cycle';

export interface DashboardTaskCatalogRow {
  taskId: string;
  family: DashboardTaskFamily;
  ownerContract: string;
  cadencePolicy: DashboardTaskCadencePolicy;
  biologicalAnchor: DashboardTaskBiologicalAnchor;
  slotPreference: DashboardTaskSlotPreference;
  dispersionWindow: DashboardTaskDispersionWindow;
  mutualExclusionGroup?: string;
  displayWindowDays: number;
  snoozeDefaultDays: number;
  decayStrategy: DashboardTaskDecayStrategy;
  metricIdRefs?: readonly string[];
  captureProtocolIdRef?: string;
  observationDimensionRef?: string;
  microActionContentRef?: string;
  featureId: string;
}

export const DASHBOARD_TASK_CATALOG: readonly DashboardTaskCatalogRow[] = ${JSON.stringify(data.rows, null, 2)} ;
`;

  writeGen('dashboard-task-catalog.gen.ts', ts);
}

// -- health-record authority -------------------------------------------------

function generateHealthRecordAuthority() {
  const registry = readYaml('health-metric-registry.yaml') as {
    groups: Array<{ groupId: string; displayName: string; rank: number }>;
    metrics: Array<Record<string, unknown>>;
  };
  const evaluationRules = readYaml('health-evaluation-rules.yaml') as {
    status_taxonomy: Array<Record<string, unknown>>;
    policies: Array<Record<string, unknown>>;
  };
  const captureProtocols = readYaml('health-capture-protocols.yaml') as {
    protocols: Array<Record<string, unknown>>;
  };
  const reminderTargets = readYaml('reminder-capture-targets.yaml') as {
    targets: Array<Record<string, unknown>>;
  };

  const groupIds = registry.groups.map((group) => group.groupId);
  const metricIds = registry.metrics.map((metric) => metric.metricId as string);
  const policyIds = evaluationRules.policies.map((policy) => policy.policyId as string);
  const protocolIds = captureProtocols.protocols.map((protocol) => protocol.protocolId as string);
  const targetRuleIds = reminderTargets.targets.map((target) => target.ruleId as string);

  const ts = `
export type HealthMetricGroupId = ${groupIds.map((id) => `'${id}'`).join(' | ')};
export type HealthMetricId = ${metricIds.map((id) => `'${id}'`).join(' | ')};
export type HealthEvaluationPolicyId = ${policyIds.map((id) => `'${id}'`).join(' | ')};
export type HealthCaptureProtocolId = ${protocolIds.map((id) => `'${id}'`).join(' | ')};
export type HealthRecordDataRuleId = ${targetRuleIds.map((id) => `'${id}'`).join(' | ')};

export type HealthValueShape = 'number' | 'enum' | 'boolean' | 'text' | 'date' | 'duration' | 'composite' | 'event';
export type HealthValueCardinality = 'single' | 'left_right_pair' | 'multi_metric_set' | 'event_payload';
export type HealthRecordKind = 'measurement' | 'assessment' | 'event' | 'status_timeline' | 'config' | 'derived';
export type HealthSourceSupport = 'manual' | 'ocr' | 'imported' | 'reminder' | 'derived';
export type HealthSafetyClass = 'descriptive' | 'professional_review_prompt' | 'no_evaluation';
export type HealthEvaluationStatus = 'on_track' | 'watch' | 'professional_review_prompt' | 'unrated' | 'missing' | 'error';
export type HealthStatusColorAlias = 'green' | 'yellow' | 'red' | 'neutral' | 'error';
export type HealthCaptureMode = 'manual' | 'prefilled' | 'guided' | 'reminder' | 'ocr_confirm';
export type HealthStorageTarget = 'health_record_event' | 'retained_table';
export type HealthDateDefaultPolicy = 'today' | 'scheduledDate' | 'dueDate';

export interface HealthMetricGroup {
  groupId: HealthMetricGroupId;
  displayName: string;
  rank: number;
}

export interface HealthApplicableAgeRange {
  startMonths: number;
  endMonths: number;
}

export type HealthApplicableSex = 'male' | 'female' | 'both';

export interface HealthMetricDefinition {
  metricId: HealthMetricId;
  groupId: HealthMetricGroupId;
  displayName: string;
  unit?: string;
  precision?: number;
  valueShape: HealthValueShape;
  valueCardinality: HealthValueCardinality;
  recordKind: HealthRecordKind;
  captureProtocolIds: readonly HealthCaptureProtocolId[];
  evaluationPolicyRef?: HealthEvaluationPolicyId;
  freshnessPolicyRef?: string;
  detailRoute?: string;
  sourceSupport: readonly HealthSourceSupport[];
  safetyClass: HealthSafetyClass;
  applicableAgeRange?: HealthApplicableAgeRange;
  applicableSex?: HealthApplicableSex;
}

export interface HealthStatusTaxonomyEntry {
  status: HealthEvaluationStatus;
  colorAlias: HealthStatusColorAlias;
  meaning: string;
}

export interface HealthEvaluationOutputRule {
  status: HealthEvaluationStatus;
  when: string;
}

export interface HealthTrendThreshold {
  thresholdId: string;
  metricIds: readonly HealthMetricId[];
  windowMonths: number;
  operator: '>=' | '>' | '<=' | '<';
  value: number;
  unit: string;
  status: HealthEvaluationStatus;
  reasonCode: string;
  boundary: string;
}

export interface HealthEvaluationPolicy {
  policyId: HealthEvaluationPolicyId;
  appliesTo: readonly HealthMetricId[];
  sourceRefs: readonly string[];
  trendThresholds?: readonly HealthTrendThreshold[];
  outputRules: readonly HealthEvaluationOutputRule[];
}

export interface HealthCaptureProtocol {
  protocolId: HealthCaptureProtocolId;
  groupId: HealthMetricGroupId;
  displayName: string;
  modeSupport: readonly HealthCaptureMode[];
  metricIds: readonly HealthMetricId[];
  requiredMetricIds: readonly HealthMetricId[];
  optionalMetricIds?: readonly HealthMetricId[];
  derivedMetricIds?: readonly HealthMetricId[];
  sourceSupport: readonly string[];
  storageTarget: HealthStorageTarget;
  completionPolicy: string;
}

export interface HealthReminderCaptureTarget {
  ruleId: HealthRecordDataRuleId;
  actionType: 'record_data';
  captureProtocolId: HealthCaptureProtocolId;
  targetMetricIds: readonly HealthMetricId[];
  dateDefaultPolicy: HealthDateDefaultPolicy;
  completionPolicy: string;
}

export const HEALTH_METRIC_GROUPS: readonly HealthMetricGroup[] = ${JSON.stringify(registry.groups, null, 2)} ;
export const HEALTH_METRICS: readonly HealthMetricDefinition[] = ${JSON.stringify(registry.metrics, null, 2)} ;
export const HEALTH_STATUS_TAXONOMY: readonly HealthStatusTaxonomyEntry[] = ${JSON.stringify(evaluationRules.status_taxonomy, null, 2)} ;
export const HEALTH_EVALUATION_POLICIES: readonly HealthEvaluationPolicy[] = ${JSON.stringify(evaluationRules.policies, null, 2)} ;
export const HEALTH_CAPTURE_PROTOCOLS: readonly HealthCaptureProtocol[] = ${JSON.stringify(captureProtocols.protocols, null, 2)} ;
export const HEALTH_REMINDER_CAPTURE_TARGETS: readonly HealthReminderCaptureTarget[] = ${JSON.stringify(reminderTargets.targets, null, 2)} ;
export const HEALTH_METRIC_IDS = ${JSON.stringify(metricIds)} as const;
export const HEALTH_CAPTURE_PROTOCOL_IDS = ${JSON.stringify(protocolIds)} as const;
export const HEALTH_EVALUATION_POLICY_IDS = ${JSON.stringify(policyIds)} as const;
export const HEALTH_RECORD_DATA_RULE_IDS = ${JSON.stringify(targetRuleIds)} as const;
`;

  writeGen('health-record.gen.ts', ts);
}

// ── growth-milestone-rules ─────────────────────────────────

function generateGrowthMilestoneRules() {
  const data = readYaml('growth-milestone-rules.yaml') as {
    rules: Array<{ ruleId: string; kind: string }>;
  };
  if (!Array.isArray(data.rules) || data.rules.length === 0) {
    throw new Error('data/structured/parentos/growth-milestone-rules.yaml must declare a non-empty rules array');
  }
  const rules = data.rules;
  const ruleIds = rules.map((rule) => rule.ruleId);
  const kinds = [...new Set(rules.map((rule) => rule.kind))].sort();
  const kindUnion = kinds.map((kind) => `'${kind}'`).join(' | ');
  const ruleIdUnion = ruleIds.map((id) => `'${id}'`).join(' | ');
  const ts = `
export type GrowthMilestoneRuleKind = ${kindUnion};
export interface GrowthMilestoneThresholdCrossedTrigger { type: 'threshold_cross'; thresholdValue: number; thresholdUnit: string; direction: 'upward' | 'downward'; evidenceWindowMonths: number; }
export interface GrowthMilestonePercentileShiftTrigger { type: 'percentile_shift'; minMagnitudePoints: number; direction: 'upward' | 'downward'; evidenceWindowMonths: number; }
export interface GrowthMilestoneRelativeChangeTrigger { type: 'relative_change'; changePercent: number; direction: 'upward' | 'downward'; valueUnit: string; evidenceWindowMonths: number; }
export type GrowthMilestoneTriggerCondition = GrowthMilestoneThresholdCrossedTrigger | GrowthMilestonePercentileShiftTrigger | GrowthMilestoneRelativeChangeTrigger;
export interface GrowthMilestoneRule { ruleId: string; kind: GrowthMilestoneRuleKind; appliesToMetricIds: readonly string[]; triggerCondition: GrowthMilestoneTriggerCondition; titleTemplate: string; deltaMagnitudeTemplate: string; deltaUnitLabel: string; }
export const GROWTH_MILESTONE_RULES = ${JSON.stringify(rules, null, 2)} as const;
export type GrowthMilestoneRuleId = ${ruleIdUnion};
export const GROWTH_MILESTONE_RULE_IDS = ${JSON.stringify(ruleIds)} as const;
`;
  writeGen('growth-milestone-rules.gen.ts', ts);
}

// -- runtime policy/catalog projections --------------------------------------

function generateAiBoundaryRules() {
  const data = readKnowledgeAsset('ai-boundary-rules') as {
    bannedTermRules: Array<Record<string, unknown>>;
    fallback: { message: string };
  };

  const ts = `
export interface AiBoundaryBannedTermRule {
  id: string;
  label: string;
  pattern: string;
  flags: string;
  boundary: string;
}

export const AI_BOUNDARY_BANNED_TERM_RULES: readonly AiBoundaryBannedTermRule[] = ${JSON.stringify(data.bannedTermRules, null, 2)};
export const AI_BOUNDARY_FALLBACK_MESSAGE = ${JSON.stringify(data.fallback.message)};
`;

  writeGen('ai-boundary.gen.ts', ts);
}

function generateAdvisorClassifier() {
  const data = readKnowledgeAsset('advisor-classifier') as {
    domainKeywords: Array<Record<string, unknown>>;
    genericRuntime: Record<string, unknown>;
  };

  const domains = data.domainKeywords.map((row) => row.domain as string);
  const ts = `
export type AdvisorClassifierDomain = ${domains.map((domain) => `'${domain}'`).join(' | ')};

export interface AdvisorDomainKeyword {
  domain: AdvisorClassifierDomain;
  keywords: readonly string[];
}

export interface AdvisorGenericRuntimeClassifier {
  phraseIncludes: readonly string[];
  exactGreetings: readonly string[];
  compactPunctuationPattern: string;
}

export const ADVISOR_DOMAIN_KEYWORDS: readonly AdvisorDomainKeyword[] = ${JSON.stringify(data.domainKeywords, null, 2)};
export const ADVISOR_GENERIC_RUNTIME: AdvisorGenericRuntimeClassifier = ${JSON.stringify(data.genericRuntime, null, 2)};
`;

  writeGen('advisor-classifier.gen.ts', ts);
}

function generatePediatricDrugCatalog() {
  const data = readKnowledgeAsset('pediatric-drug-catalog') as {
    drugs: Array<Record<string, unknown>>;
  };

  const ts = `
export interface PediatricDrug {
  id: string;
  name: string;
  generic?: string;
  unit: string;
  altUnits?: readonly string[];
  frequency: string;
  py: string;
  tags?: readonly string[];
  aliases?: readonly string[];
}

export const PEDIATRIC_DRUGS: readonly PediatricDrug[] = ${JSON.stringify(data.drugs, null, 2)};
`;

  writeGen('pediatric-drug-catalog.gen.ts', ts);
}

function generateJournalGuidanceCatalog() {
  const data = readKnowledgeAsset('journal-guidance-catalog') as {
    guidedPrompts: Array<Record<string, unknown>>;
    guidedPromptFallback: Record<string, unknown>;
    observationNudges: Array<Record<string, unknown>>;
    observationNudgeFallback: Record<string, unknown>;
  };

  const ts = `
export interface JournalGuidedPrompt {
  ruleId: string;
  prompts: readonly string[];
}

export interface JournalGuidedPromptFallback {
  observedChangeTemplate: string;
  responseEffect: string;
}

export interface ObservationNudgeCopy {
  dimensionId: string;
  variants: readonly string[];
}

export interface ObservationNudgeFallback {
  template: string;
}

export const JOURNAL_GUIDED_PROMPTS: readonly JournalGuidedPrompt[] = ${JSON.stringify(data.guidedPrompts, null, 2)};
export const JOURNAL_GUIDED_PROMPT_FALLBACK: JournalGuidedPromptFallback = ${JSON.stringify(data.guidedPromptFallback, null, 2)};
export const OBSERVATION_NUDGE_COPY: readonly ObservationNudgeCopy[] = ${JSON.stringify(data.observationNudges, null, 2)};
export const OBSERVATION_NUDGE_FALLBACK: ObservationNudgeFallback = ${JSON.stringify(data.observationNudgeFallback, null, 2)};
`;

  writeGen('journal-guidance.gen.ts', ts);
}

function generateSmartAlertRules() {
  const data = readKnowledgeAsset('smart-alert-rules') as Record<string, unknown>;

  const ts = `
export type SmartAlertPriority = 'P0' | 'P1' | 'P2';
export type DynamicTaskSource = 'allergy-followup' | 'dental-followup' | 'seasonal-alert';
export type AllergyFollowupCondition =
  | 'anaphylaxis'
  | 'skin_without_anaphylaxis'
  | 'respiratory_without_anaphylaxis'
  | 'gastrointestinal'
  | 'severe_without_anaphylaxis';

export interface AllergenNormalizationRule {
  match: string;
  tags: readonly string[];
}

export interface ReminderTagAllergenRule {
  ruleTag: string;
  allergenTags: readonly string[];
}

export interface ChronicConditionDetector {
  conditionId: string;
  sourceField: 'allergen' | 'notes';
  keywords: readonly string[];
}

export interface AllergyCollisionMessages {
  dangerTemplate: string;
  nonDangerTemplate: string;
}

export interface AllergyFollowupSymptomGroups {
  skin: readonly string[];
  respiratory: readonly string[];
  gastrointestinal: readonly string[];
  anaphylaxis: readonly string[];
}

export interface AllergyFollowupTemplate {
  templateId: string;
  condition: AllergyFollowupCondition;
  idPrefix: string;
  offsetDays: number;
  titleTemplate: string;
  descriptionTemplate: string;
  domain: string;
  priority: SmartAlertPriority;
  source: DynamicTaskSource;
}

export interface DentalFollowupRule {
  eventType: string;
  months: number;
  title: string;
}

export interface SeasonalAlertRule {
  id: string;
  title: string;
  description: string;
  activeMonths: readonly number[];
  requiredConditions: readonly string[];
  priority: Exclude<SmartAlertPriority, 'P0'>;
}

export interface MedicalAlertRule {
  thresholdCount?: number;
  windowDays?: number;
  followupWindowDays?: number;
  recentWindowDays?: number;
  level: 'info' | 'warning' | 'danger';
  title?: string;
  titleTemplate?: string;
  messageTemplate: string;
}

export interface SmartAlertMedicalRules {
  frequentVisits: MedicalAlertRule;
  repeatedDiagnosis: MedicalAlertRule;
  severeWithoutFollowup: MedicalAlertRule;
  longTermMedication: MedicalAlertRule;
}

export const ALLERGEN_NORMALIZATION_RULES: readonly AllergenNormalizationRule[] = ${JSON.stringify(data.allergenNormalization, null, 2)};
export const REMINDER_TAG_ALLERGEN_RULES: readonly ReminderTagAllergenRule[] = ${JSON.stringify(data.reminderTagAllergenMap, null, 2)};
export const CHRONIC_CONDITION_DETECTORS: readonly ChronicConditionDetector[] = ${JSON.stringify(data.chronicConditionDetectors, null, 2)};
export const ALLERGY_COLLISION_MESSAGES: AllergyCollisionMessages = ${JSON.stringify(data.allergyCollisionMessages, null, 2)};
export const ALLERGY_FOLLOWUP_SYMPTOM_GROUPS: AllergyFollowupSymptomGroups = ${JSON.stringify(data.allergyFollowupSymptomGroups, null, 2)};
export const ALLERGY_FOLLOWUP_TEMPLATES: readonly AllergyFollowupTemplate[] = ${JSON.stringify(data.allergyFollowupTemplates, null, 2)};
export const DENTAL_FOLLOWUP_RULES: readonly DentalFollowupRule[] = ${JSON.stringify(data.dentalFollowups, null, 2)};
export const DENTAL_FOLLOWUP_DESCRIPTION_TEMPLATE = ${JSON.stringify(data.dentalFollowupDescriptionTemplate)};
export const SEASONAL_ALERT_RULES: readonly SeasonalAlertRule[] = ${JSON.stringify(data.seasonalAlerts, null, 2)};
export const SMART_ALERT_MEDICAL_RULES: SmartAlertMedicalRules = ${JSON.stringify(data.medicalAlerts, null, 2)};
`;

  writeGen('smart-alert-rules.gen.ts', ts);
}

// -- knowledge asset projection fingerprints -------------------------------

function generateKnowledgeAssetProjectionFingerprints() {
  const fingerprints = Object.fromEntries(
    KNOWLEDGE_ASSET_IDS.map((assetId) => {
      const asset = loadKnowledgeAssetForProjection(assetId);
      return [
        assetId,
        {
          projectionFingerprint: asset.projectionFingerprint,
          schemaVersion: asset.manifest.schemaVersion,
          contentVersion: asset.manifest.contentVersion,
          authorityClass: asset.manifest.authorityClass,
        },
      ];
    }),
  );

  const ts = `
export interface KnowledgeAssetProjectionFingerprint {
  projectionFingerprint: string;
  schemaVersion: number;
  contentVersion: string;
  authorityClass: string;
}

export const KNOWLEDGE_ASSET_PROJECTION_FINGERPRINTS: Record<string, KnowledgeAssetProjectionFingerprint> = ${JSON.stringify(fingerprints, null, 2)};
`;

  writeGen('knowledge-asset-fingerprints.gen.ts', ts);
}

// ── Main ───────────────────────────────────────────────────

console.log('Generating ParentOS knowledge base...');
generateReminderRules();
generateMilestoneCatalog();
generateSensitivePeriods();
generateObservationFramework();
generateGrowthStandards();
generateNurtureModes();
generateKnowledgeSourceReadiness();
generateDashboardTaskCatalog();
generateHealthRecordAuthority();
generateGrowthMilestoneRules();
generateAiBoundaryRules();
generateAdvisorClassifier();
generatePediatricDrugCatalog();
generateJournalGuidanceCatalog();
generateSmartAlertRules();
generateKnowledgeAssetProjectionFingerprints();
console.log('Done.');
