// @generated - do not edit manually
// Generated by scripts/generate-knowledge-base.ts

pub(crate) static VACCINE_REMINDER_RULE_IDS: &[&str] = &[
    "PO-REM-VAC-001",
    "PO-REM-VAC-002",
    "PO-REM-VAC-003",
    "PO-REM-VAC-004",
    "PO-REM-VAC-005",
    "PO-REM-VAC-006",
    "PO-REM-VAC-007",
    "PO-REM-VAC-008",
    "PO-REM-VAC-009",
    "PO-REM-VAC-010",
    "PO-REM-VAC-011",
    "PO-REM-VAC-012",
    "PO-REM-VAC-013",
    "PO-REM-VAC-014",
    "PO-REM-VAC-015",
    "PO-REM-VAC-016",
    "PO-REM-VAC-017",
    "PO-REM-VAC-050",
    "PO-REM-VAC-051",
    "PO-REM-VAC-052",
    "PO-REM-VAC-053",
];
